# Generated by Django 5.2.1 on 2025-05-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content',
            field=models.TextField(default='No content yet'),
            preserve_default=False,
        ),
    ]
